import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="grid h-full place-content-center">
        <h1 className="animate-bounce text-4xl font-bold">Hello Next.js!</h1>
      </main>
    </>
  );
};

export default Home;
